---
title: "Your Project Title"
author: 
  - "Alex Delamer"
  - "Duc Hoang"
  - "Aatish Prasad"
  - "Kishori Akola"
date: today
format: 
  html:
    toc: true
    number-sections: true
  pdf:
    toc: true
    number-section: true
bibliography: references.bib
execute:
  echo: false
  output: true
  warning: false
  message: false
---

## Test

@ramos_e-commerce_nodate

```{r setup}
library(tidyverse)
library(lubridate)
library(janitor)
library(knitr)
library(stringr)
library(ggplot2)
```

```{r}
## Data Loading
sales_data <- read_csv("data/Sales Transaction v.4a.csv")

glimpse(sales_data)

```
```{r}
## Data Cleaning
sales_clean <- sales_data |>
  clean_names() |>
  mutate(
    date = mdy(date),
    revenue = price * quantity,
    year = year(date),
    month = month(date, label = TRUE),
    year_month = floor_date(date, "month"),
    transaction_type = if_else(
      quantity < 0 | str_starts(transaction_no, "C"),
      "Cancelled/Return",
      "Sale"
    )
  )

```


```{r}
#Checking the percentage of the UK and Non UK countries on the basis of transaction number
transaction_percentage <- sales_clean |>
  mutate(
    market = if_else(
      country == "United Kingdom",
      "United Kingdom",
      "Non-UK"
    )
  ) |>
  distinct(transaction_no, market) |>
  count(market, name = "number_of_transactions") |>
  mutate(
    percentage = round(number_of_transactions / sum(number_of_transactions) * 100, 2)
  )

transaction_percentage
```


```{r}
# Clean transaction id
sales_clean <- sales_clean |> 
  mutate(
  transaction_no = str_remove(transaction_no, "^C")
) |> 
  group_by(transaction_no) |> 
  mutate(
    total_revenue = sum(revenue, na.rm = TRUE)
  ) |> 
  ungroup()

# Distinct transactions
dist_trans <- sales_clean |> 
  distinct(transaction_no, .keep_all = TRUE)
```




```{r}
#| label: fig-UK_line
#| fig-cap: Number of UK Transactions by Month
# Count of transactions over time in UK
dist_trans |>
  filter(country == "United Kingdom") |>
  count(year_month) |>
  ggplot(aes(year_month, n)) +
  geom_line() +
  geom_point() +
  scale_x_date(
    date_breaks = "1 month",
    date_labels = "%b %Y"
  ) +
  labs(
    x = "Month",
    y = "Transactions"
  ) +
  theme_minimal() +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1)
  )
```


```{r}
#| label: fig-Int_line
#| fig-cap: Number of Global Transactions by Month
# Count of International transactions over time 
dist_trans |>
  filter(country != "United Kingdom") |>
  count(year_month) |>
  ggplot(aes(year_month, n)) +
  geom_line() +
  geom_point() +
  scale_x_date(
    date_breaks = "1 month",
    date_labels = "%b %Y"
  ) +
  labs(
    x = "Month",
    y = "Transactions"
  ) +
  theme_minimal() +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1)
  )
```

